name: Crawl and Blur Faces

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.10

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgl1-mesa-glx libglib2.0-0 build-essential cmake libopenblas-dev liblapack-dev libx11-dev libgtk-3-dev
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run crawler
      run: python crawl_website.py

    - name: Commit and push crawler results
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Add crawled website data"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Run face blurring
      run: python blur_faces.py

    - name: Commit and push blurred images
      run: |
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        git add .
        git commit -m "Add blurred images"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload results
      uses: actions/upload-artifact@v2
      with:
        name: blurred-images
        path: blurred_images
